---
title: "Laboratorio5"
author: "MarioPisquiy"
date: "2022-10-02"
output: rmarkdown::github_document
always_allow_html: true
---

```{r include = FALSE}

library(lubridate)
library(readxl)
library(nycflights13)
library(dplyr)
library(stringr)
library(plotly)
library(highcharter)
library(knitr)
webshot::install_phantomjs()
```


## Ejercicio 1

```{r echo = FALSE}

#Variable que guarda el último eclipse
start_date <- ymd_hms("2017 august 21 18:26:40")

#Variable que guarda el valor de un synodic_month
synodic_month <- days(29) + hours(12) + minutes(44) + seconds(3)

#Variable que guarda un saros
saros <- synodic_month * 223

#Siguiente eclipse
for (i in 1: 223)
{
  if (i == 1){
    next_date <- start_date + synodic_month  
  }
  else{
    next_date <- next_date + synodic_month
  }
}
print(paste("La fecha del último eclipse fue:", start_date,"y el siguiente eclipse será:",next_date, sep = " "))
```


## Ejercicio 2

```{r echo = FALSE}

data <- read_excel("data.xlsx")
colnames(data) <- c("fecha_creacion","hora_creacion","caller_id","cod","email","sms","call","fecha_final","hora_final")

fechas_num <- data
fechas_dis <- data
fechas_num$fecha_creacion <- format((as_date(as.numeric(fechas_num$fecha_creacion), origin = dmy("30/12/1899"))), "%d-%m-%Y")
fechas_num$fecha_creacion <- dmy(fechas_num$fecha_creacion)

fechas_dis$fecha_creacion <- dmy(fechas_dis$fecha_creacion)

fechas_dis <- fechas_dis[!is.na(fechas_dis$fecha_creacion),]

fechas_num <- fechas_num[!is.na(fechas_num$fecha_creacion),]

data <- bind_rows(fechas_dis, fechas_num)

fechas_num <- data
fechas_dis <- data
fechas_num$fecha_final <- format((as_date(as.numeric(fechas_num$fecha_final), origin = dmy("30/12/1899"))), "%d-%m-%Y")
fechas_num$fecha_final <- dmy(fechas_num$fecha_final)

fechas_dis$fecha_final <- dmy(fechas_dis$fecha_final)

fechas_dis <- fechas_dis[!is.na(fechas_dis$fecha_final),]

fechas_num <- fechas_num[!is.na(fechas_num$fecha_final),]
data <- bind_rows(fechas_dis, fechas_num)

options(dplyr.summarise.inform = FALSE)

categoria1 <- data %>%
  mutate(mes = month(fecha_creacion))%>%
  select(caller_id,mes,cod)%>%
  filter(cod == '0')%>%
  group_by(cod,mes)%>%
  summarise(cantidad = n())%>%
  arrange(desc(cantidad)) %>%
  head(1)

categoria2 <- data %>%
  mutate(mes = month(fecha_creacion))%>%
  select(caller_id,mes,cod)%>%
  filter(cod == 'Actualización de Información')%>%
  group_by(cod,mes)%>%
  summarise(cantidad = n())%>%
  arrange(desc(cantidad)) %>%
  head(1)

categoria3 <-data %>%
  mutate(mes = month(fecha_creacion))%>%
  select(caller_id,mes,cod)%>%
  filter(cod == 'Cancelaciones')%>%
  group_by(cod,mes)%>%
  summarise(cantidad = n())%>%
  arrange(desc(cantidad)) %>%
  head(1)

categoria4 <- data %>%
  mutate(mes = month(fecha_creacion))%>%
  select(caller_id,mes,cod)%>%
  filter(cod == 'Cobros')%>%
  group_by(cod,mes)%>%
  summarise(cantidad = n())%>%
  arrange(desc(cantidad)) %>%
  head(1)

categoria5 <- data %>%
  mutate(mes = month(fecha_creacion))%>%
  select(caller_id,mes,cod)%>%
  filter(cod == 'Consultas')%>%
  group_by(cod,mes)%>%
  summarise(cantidad = n())%>%
  arrange(desc(cantidad)) %>%
  head(1)

categoria6 <- data %>%
  mutate(mes = month(fecha_creacion))%>%
  select(caller_id,mes,cod)%>%
  filter(cod == 'Empresarial')%>%
  group_by(cod,mes)%>%
  summarise(cantidad = n())%>%
  arrange(desc(cantidad)) %>%
  head(1)

categoria7 <- data %>%
  mutate(mes = month(fecha_creacion))%>%
  select(caller_id,mes,cod)%>%
  filter(cod == 'Otros/Varios')%>%
  group_by(cod,mes)%>%
  summarise(cantidad = n())%>%
  arrange(desc(cantidad)) %>%
  head(1)

categorias <- rbind(categoria1,categoria2,categoria3,categoria4,categoria5,categoria6,categoria7)
categorias <- as.data.frame(categorias)
knitr::kable(categorias )

dia<-data %>%
  mutate(dia = wday(fecha_creacion))%>%
  select(caller_id,dia)%>%
  group_by(dia)%>%
  summarise(cantidad = n())%>%
  arrange(desc(cantidad)) %>%
  head(1)

print(paste("El dia de la semana con mas llamadas es el lunes (",dia$dia,")",sep=""))

mes_ocupado <- data %>%
  mutate(mes = month(fecha_creacion))%>%
  select(caller_id,mes)%>%
  group_by(mes)%>%
  summarise(cantidad = n())%>%
  arrange(desc(cantidad)) %>%
  head(1)

print(paste("El mes mas ocupado es:",mes_ocupado$mes,sep=" "))

llamadas_dia <- data %>%
  mutate(dia = day(fecha_creacion)) %>%
  select(caller_id,dia)%>%
  group_by(dia)%>%
  summarise(cantidad = n())
print("No hay una estacionalidad de llamadas al mes, pero los ultimos dias se suelen recibir menos que el resto del mes")

data <- data%>%
  mutate(duracion_llamada = difftime(hora_final,hora_creacion,units="mins"))

promedio <- data%>%
  select(caller_id,duracion_llamada)%>%
  summarise(promedio = round(mean(duracion_llamada),digits = 0))

print(paste("El promedio de duración de las llamadas es:",promedio$promedio,sep=" "))

frecuencias <- data%>%
  select(caller_id,duracion_llamada)%>%
  group_by(duracion_llamada)%>%
  summarise(cantidad = n())

frecuencias <- as.data.frame(frecuencias)
knitr::kable(frecuencias)

```


## Ejercicio 3

```{r echo = FALSE}

fecha_nacimiento <- ymd("2002 may 26")
print(fecha_nacimiento)
mes <- month(fecha_nacimiento)
dia <- day(fecha_nacimiento)

if (mes == 1){
  if(dia < 20){
    signo <- "Capricornio"
  }else{
    signo <- "Acuario"
  }
}else if (mes == 2){
  if(dia < 19){
    signo <- "Acuario"
  }else{
    signo <- "Piscis"
  }
}else if (mes == 3){
  if(dia < 21){
    signo <- "Piscis"
  }else{
    signo <- "Aries"
  }
}else if (mes == 4){
  if(dia < 20){
    signo <- "Aries"
  }else{
    signo <- "Tauro"
  }
}else if (mes == 5){
  if(dia < 21){
    signo <- "Tauro"
  }else{
    signo <- "Geminis"
  }
}else if (mes == 6){
  if(dia < 21){
    signo <- "Geminis"
  }else{
    signo <- "Cancer"
  }
}else if (mes == 7){
  if(dia < 23){
    signo <- "Cancer"
  }else{
    signo <- "Leo"
  }
}else if (mes == 8){
  if(dia < 23){
    signo <- "Leo"
  }else{
    signo <- "Virgo"
  }
}else if (mes == 9){
  if(dia < 23){
    signo <- "Virgo"
  }else{
    signo <- "Libra"
  }
}else if (mes == 10){
  if(dia < 23){
    signo <- "Libra"
  }else{
    signo <- "Escorpio"
  }
}else if (mes == 11){
  if(dia < 22){
    signo <- "Escorpio"
  }else{
    signo <- "Sagitario"
  }
}else if (mes == 12){
  if(dia < 22){
    signo <- "Sagitario"
  }else{
    signo <- "Capricornio"
  }
}
cat("Su signo zodiacal es: ", signo)

```


## Ejercicio 4

```{r echo = FALSE}

vuelos <- flights

vuelos <- vuelos %>%
  filter(!is.na(dep_time)) %>%
  mutate(dep_time_completo = (ymd_hm(paste(year,month,day,paste(floor(dep_time/100),":",round((dep_time/100-floor(dep_time/100))*100,digits=0), sep=""),sep=" "))))
  
vuelos <- vuelos %>%
  filter(!is.na(sched_dep_time)) %>%
  mutate(sched_dep_time_completo = (ymd_hm(paste(year,month,day,paste(floor(sched_dep_time/100),":",round((sched_dep_time/100-floor(sched_dep_time/100))*100,digits=0), sep=""),sep=" "))))

vuelos <- vuelos %>%
  filter(!is.na(arr_time)) %>%
  mutate(arr_time_completo = (ymd_hm(paste(year,month,day,paste(floor(arr_time/100),":",round((arr_time/100-floor(arr_time/100))*100,digits=0), sep=""),sep=" "))))

vuelos <- vuelos %>%
  filter(!is.na(sched_arr_time)) %>%
  mutate(sched_arr_time_completo = (ymd_hm(paste(year,month,day,paste(floor(sched_arr_time/100),":",round((sched_arr_time/100-floor(sched_arr_time/100))*100,digits=0), sep=""),sep=" "))))

vuelos <- vuelos %>%
  filter(!is.na(dep_delay)) %>%
  mutate(total_delay = minutes(dep_delay+arr_delay))

data <- as.data.frame(data)
knitr::kable(data %>% sample_n(50))

```


