

library(shiny)
library(lubridate)

shinyUI(fluidPage(
    
    titlePanel("Shiny Inputs Glossary"),

    
    sidebarLayout(
        sidebarPanel(
            h1("Inputs"),
            numericInput("ninput","Ingrese un numero:",
                          value = 10, step =10),
            sliderInput('slinput','Seleccione un porcentaje:',
                        min = 0, max = 100, step = 1, value = 0, 
                        post='%'),
            sliderInput('slinputmulti','Seleccione Rango:',
                        value = c(10000,30000), 
                        min = 0, 
                        max = 150000, 
                        step = 1000, 
                        pre='Q',
                        sep = ','),
            sliderInput('slinputanimate','Pasos:',
                        value = 0, 
                        min = 0, 
                        max = 100,
                        step = 10,
                        animate = TRUE),
            dateInput('date_input','Ingrese fecha: ',
                      value = Sys.Date(),
                      language = 'es',
                      weekstart = 1,
                      format='dd-mm-yyyy'),
            dateRangeInput('date_range_input',
                           'Seleccione fechas',
                           start = today()-15,
                           end = today(),
                           max = today(),
                           min = today()-365,
                           language = 'es',
                           sep=' hasta '),
            selectInput('select_input','Selecciones estado: ', 
                        choices = state.name,
                        selected = state.name[sample(1:length(state.name),size=1)]),
            selectInput('select_input_2','Seleccione letras:',
                        choices = letters,
                        selected = 'a',
                        multiple = TRUE),
            checkboxInput('chkbox_input','Mostrar resumen', 
                          value = FALSE),
            checkboxGroupInput('chkbox_group_input',
                               'Seleccione opcion: ',
                               choices = letters[1:3],
                               selected = NULL),
            radioButtons('radio_buttons','Seleccione nivel academico',
                         choices = c('Primaria'=1,
                                     'Basico'=2,
                                     'Bachillerato'=3,
                                     'Licenciatura'=4,
                                     'Maestria'=5,
                                     'Doctorado'=6)),
            actionButton('action','correr',icon= icon('database')),
            submitButton()
        ),

        mainPanel(
            h1("Outputs"),
            h2("numeric input"),
            verbatimTextOutput('out_numeric_input'),
            h2("slider input"),
            h3('Slider Input Simple'),
            verbatimTextOutput('out_slider_input'),
            h3('Slider Input Multiple'),
            verbatimTextOutput('out_slider_input_multi'),
            h3('Slider Input Animado'),
            verbatimTextOutput('out_slider_input_ani'),
            h2('Date Input'),
            h3('Date Input Simple'),
            verbatimTextOutput('out_date_input'),
            h3('Date Input Rango'),
            verbatimTextOutput('out_date_range_input'),
            h2('Select Input'),
            h3('Select Input Simple'),
            verbatimTextOutput('out_select_input'),
            h3('Select Input Multiple'),
            verbatimTextOutput('out_select_input_multi'),
            h2('Check Box Input'),
            h3('Check Box Inpu Simple'),
            verbatimTextOutput('out_checkbox'),
            h3('Check Box Input Multiple'),
            verbatimTextOutput('out_checkbox_multi'),
            h2('Radio Buttons Input'),
            verbatimTextOutput('out_radio'),
            h2('Action Button'),
            verbatimTextOutput('out_action')
        )
    )
))
