---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(dplyr)
```

```{r data}
videos <- read_csv("academatica_videos.csv")
video_stats <- read_csv("academatica_video_stats.csv")
videos_metadata <- read_csv("academatica_videos_metadata.csv")
```


```{r kpis}
metricas <- video_stats %>%
  summarise(tot_views = sum(viewCount), 
           tot_likes = sum(likeCount), 
           tot_dislikes = sum(dislikeCount), 
           tot_favorite = sum(favoriteCount), 
           tot_comments = sum(commentCount)) 
```


# metrica {data-icon=fa-ruler}

row
------------------------

### Reproducciones

```{r}
valueBox(metricas$tot_views,icon='fa-eye',color='success')
```


### Likes

```{r}
valueBox(metricas$tot_likes,icon='fa-thumbs-up',color='warning')
```


### Comentarios

```{r}
valueBox(metricas$tot_comments,icon='fa-comment',color='danger')
```


row
-----------------------

### Likes

```{r}
rlikes <- metricas$tot_likes/(metricas$tot_likes+metricas$tot_dislikes)
rlikes <- round(rlikes,2)*100
gauge(rlikes,min=0,max=100,symbol='%',
      gaugeSectors(success=c(80,100),
                   warning = c(40,79),
                   danger =c(0,39)))
```


### Dislikes

```{r}
rdlikes <- metricas$tot_dislikes/(metricas$tot_likes+metricas$tot_dislikes)
rdlikes <- round(rdlikes,2)*100
gauge(rdlikes,min=0,max=100,symbol='%',
      gaugeSectors(danger=c(80,100),
                   warning = c(40,79),
                   success =c(0,39)))
```


row 
-------------------------

###
